LikeLion-at-DGU/2025-simba-2-marblekiri

main/templates/main/start.html

👷 작업한 내용
- merge 하기 전, main/start.html 커밋하기

[FE] feat: main/start.html 커밋하기

---

main/views.py
questions.json

👷 작업한 내용
- dbsqlite3은 개인로컬에서만 작업하다보니 json 파일을 추가하여 db파일을 공유하여 에러 해결하고자 합니다!

[BE] feat: db 오류 해결을 위해 json 파일 추가

---

main/templates/main/result.html
main/views.py

[BE] fix : views.py 저장 오류 수정

---

main/templates/main/setup.html
marblekiri/static/css/setup.css
marblekiri/static/js/setup.js

👷 작업한 내용
- setup.html 인원설정 추가/삭제 기능 구현
- setup.html 게임설정 슬라이더 기능 구현

[FE]feat:setup.html 기능 구현

---

main/templates/main/game.html
marblekiri/static/css/base/style.css
marblekiri/static/js/game.js

👷 작업한 내용
- 말 이동 표현
- game.html (tile index 추가)
- game.js ( 말 이동 함수 추가 )
- style.css ( 말 css )

[BE] feat: 말 이동 표현 완료

---

main/templates/main/game.html
main/views.py

👷 작업한 내용
- 보드판 index 시작 위치 수정 (game_start 함수 /  views.py)

[BE] fix : 보드판 index 시작 위치 수정

---

main/templates/main/game.html
marblekiri/static/css/base/style.css
marblekiri/static/js/game.js

👷 작업한 내용
- 미션 박스 생성 ( but 위치 수정 필요 )

[BE] feat : 미션 박스 생성 ( but 위치 수정 필요 )

---

main/templates/main/game.html
marblekiri/static/js/game.js

👷 작업한 내용
- 미션 목록 누적하여 띄우도록 복원, 번호매김 수정 (0~9로 되는 것 인덱스 보여주도록 수정)

[BE] fix: 미션 목록 누적하여 띄우도록 복원, 번호매김 수정

---

main/templates/main/game.html
main/views.py
marblekiri/static/css/base/style.css
marblekiri/static/js/game.js

👷 작업한 내용
- 말 위치 버그 수정 
버튼 눌렀을 때 페이지 reload 되는 현상 수정 -> json 형식으로 FETCH 전달
- handle_action views.py 기능 별 분리
- process_action(player, action) / advance_turn(room, total_players) / handle_action(request)

[BE] fix: 말 위치 버그 수정/ Refactor: handle_action views.py 기능 별 분리

---

main/templates/main/game.html
marblekiri/static/js/game.js

[BE] feat: 도착한 칸의 미션 목록 누적해서 띄우기

---

main/templates/main/game.html
main/templates/main/setup.html
main/views.py
marblekiri/static/js/game.js
marblekiri/static/js/setup.js

👷 작업한 내용
- fix: 랭킹 수정 (새고X ver) 중간 커밋

[BE] fix: 랭킹 수정 (새고X ver) 중간 커밋

---

main/templates/main/game.html
marblekiri/static/js/game.js

[BE] feat : 주사위 / 미션 버튼 로직 완료

---

main/templates/main/custom_questions.html
main/templates/main/game.html
main/templates/main/result.html
main/views.py
marblekiri/static/css/base/style.css
marblekiri/static/css/result.css

[FE] feat : theme 별 body background  색 변경

[FE] theme 별 body background  색 변경

---

main/templates/main/game.html
marblekiri/static/css/base/style.css
marblekiri/static/js/game.js

👷 작업한 내용
- 모달 스타일 추가
- 모달 구조 수정

[FE]feat: 보드 판 모달 기능 추가

---

main/templates/main/game.html
marblekiri/static/js/game.js
marblekiri/static/js/setup.js

👷 작업한 내용
- 모달창 페이지 이동 오류
- 테마 미선택 alert 오류

[BE] fix: 모달창 페이지 이동 오류 / 테마 미선택 alert 오류 해결

---

main/views.py
marblekiri/static/css/base/style.css
marblekiri/static/js/game.js
marblekiri/static/js/setup.js

👷 작업한 내용
- 랭킹 안 보기 옵션일 경우 통과 마셔 가 안 눌러짐 -> 랭킹 업데이트하지 않도록 수정
- 커스텀 옵션일 때 랭킹이 안 보임 -> 보이도록 수정
- board 말 첫 위치 수정 -> 첫 칸으로 top 위치 수정

[BE] fix: 커스텀 랭킹 옵션 체크 / style: 보드 말 위치 수정

---

main/templates/main/result.html
main/views.py
marblekiri/static/css/result.css
marblekiri/static/js/result.js

👷 작업한 내용
-result.html db 연결 완료

[BE] feat: result.html db 연결 완료

---

main/templates/main/result.html
marblekiri/static/css/base/style.css
marblekiri/static/css/result.css

👷 작업한 내용
- result.html 박스 색 테마 맞춤 
- game + result 배경 색 피그마대로

[FE] feat: result.html 박스 색 테마 맞춤 / game + result 배경 색 피그마대로

---

marblekiri/static/css/start.css

[FE] style: dice 크기 조정

---

main/templates/main/result.html
marblekiri/static/css/result.css

👷 작업한 내용
- result 페이지 테마 맞춤 + 사진 업로드 디자인 수정

[FE] feat: result 페이지 테마 맞춤 + 사진 업로드 디자인 수정

---

main/templates/main/game.html
marblekiri/static/css/base/style.css

👷 작업한 내용
- 통과 / 마셔 / 주사위 굴리기 비활성화 시 색깔 변경
- style.css 수정

[FE] fix: 주사위 굴리기 비활성화 수정

---

main/templates/main/result.html
marblekiri/static/css/result.css

👷 작업한 내용
- result 페이지 미션 list data 연결 
- 사진 랭킹 여부에 따라 크기 수정

[FE] feat: result 페이지 미션 list data 연결 / 사진 랭킹 여부에 따라 크기 수정

---

main/templates/main/custom_questions.html
main/views.py
marblekiri/static/css/custom_questions.css
marblekiri/static/js/custom.js

👷 작업한 내용
- custom_questions 페이지
1. js 별도 파일 분리, custom 질문 추가 및 삭제 시 번호 재정렬 되도록
2. css 작성
3. 질문 추가 버튼도 구역별로 서식 적용되도록 수정

[BE] feat: custom 페이지 js, css 작성

---

main/templates/main/game.html
main/views.py
marblekiri/static/css/base/style.css
marblekiri/static/js/game.js

👷 작업한 내용
- 랭킹 처음 들어왔을 때 보이도록 수정
- 보드판 화면 비율 90으로 수정
- views.py 수정

views.py 및 game.js 수정 후 upstream 병합

---

marblekiri/static/css/base/style.css

👷 작업한 내용
- mission 이중 스크롤 수정
- css 수정

[FE] fix: missions 이중 스크롤 수정

---

main/templates/main/game.html
marblekiri/static/js/game.js

👷 작업한 내용
- mission-list를 20칸 고정된 <li> 구조로 렌더링하도록 수정
- 주사위 결과에 따라 해당 data-index 위치에 미션 텍스트 삽입
- visitedTiles Set으로 중복 미션 삽입 방지
- 기존 append 방식 제거, 성능 개선
- css 적용 안함

[FE] feat: 미션 리스트 20칸 고정 및 인덱스 기반 질문 삽입 구현/css 적용안함

---

main/templates/main/setup.html
marblekiri/static/css/setup.css
marblekiri/static/js/setup.js

👷 작업한 내용
- design: 설정의 설명 글씨체, 중앙정렬

[FE]feat: setup 디자인 변경

---

marblekiri/static/css/setup.css
marblekiri/static/css/start.css

👷 작업한 내용
- fix: setup.html의 container 태그 수정
- desgin: start 페이지의 크기 고정, 스크롤 고정

[FE]feat: start 크기 고정

---

main/templates/main/setup.html
marblekiri/static/css/setup.css
marblekiri/static/js/setup.js

👷 작업한 내용
- feat: 진행 바퀴 수 버튼 클릭시 슬라이더 활성화
- design: 활성화 시 색깔 바꾸기
- design: 게임 스타트 버튼 활성화 시 디자인 수정

[FE]feat: game-options 수정

---

main/templates/main/game.html
marblekiri/static/css/base/style.css

👷 작업한 내용
- 미션 목록 HTML 구조 개선 (mission-number, mission-text로 분리하여 정렬 이슈 해결)
- mission-item에 flex row 적용 및 좌측 여백 정리
- mission-spacer 요소 도입으로 스크롤 리스트 상하단 여백 확보
- mission-list에 border, padding, background 추가
- 스크롤바 숨김 처리 (scrollbar-width, ::-webkit-scrollbar)
- mission-spacer에 동일한 회색 배경 적용 (#E8E8E8)
- JS에서 .mission-text에 텍스트 동적 삽입 처리

[FE] 미션 목록 UI 개선 및 정렬 기능 리팩토링

---

marblekiri/static/css/custom_questions.css

👷 작업한 내용
- style: custom 페이지도 폰트 적용

[BE] style: custom 페이지도 폰트 적용

---

main/templates/main/setup.html
marblekiri/static/css/setup.css

👷 작업한 내용
- feat: 인원 삭제 버튼 hover시 테마색상과 동일하게 적용
- feat: 인원 삭제 버튼 선택시 테마색상과 동일하게 적용
- design: toggle의 span 위치 바꾸기
- design: 인원 이름리스트의 크기 고정시키기 (flex-shrink=0;)

[FE]feat: setup 토클, 버튼 수정

---

marblekiri/static/css/game.css

👷 작업한 내용
- feat: custom 페이지의 미션리스트. 글자 수의 따라 박스 크기 늘리기

[FE]feat: custom 미션리스트 수정

---

main/templates/main/start.html
marblekiri/static/css/start.css

👷 작업한 내용
- design: start.css에서 start_button에 margin으로 위치 조정

[FE]feat: start.css 수정

---

main/templates/main/setup.html
main/views.py

👷 작업한 내용
- 턴 -> 바퀴 수로 view.py + html 변경

[BE] fix: 턴 -> 바퀴 수로 view.py + html 변경

---

main/templates/main/custom_questions.html
marblekiri/static/css/custom_questions.css

👷 작업한 내용
- design: custom_questions.css 가독성 up!!

[FE]feat: custom_questions.css 수정

---

questions.json

👷 작업한 내용
- db.sqlite3 -> json으로 커밋

[BE] db.sqlite3 -> json으로 커밋
